apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: default
  name: cronjob-crawler
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: crawler
        spec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - crawler
                topologyKey: topology.kubernetes.io/zone
          containers:
          - name: write-file
            image: irisowo/crawler:v1
            volumeMounts:
            - name: history-dir
              mountPath: /sample_crawler/history
          restartPolicy: OnFailure
          volumes:
          - name: history-dir
            persistentVolumeClaim:
              claimName: pvc-demo