apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: default
  name: cronjob-crawler
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector: 
            app-type: crawler
          containers:
          - name: write-file
            image: irisowo/crawler:v1
            volumeMounts:
            - name: history-dir
              mountPath: /sample_crawler/history
          restartPolicy: OnFailure
          volumes:
          - name: history-dir
            persistentVolumeClaim:
              claimName: pvc-demo