name: Build up docker file
on:
  workflow_dispatch:
  push:
    paths:
      - 'cron/Dockerfile'
      - 'cron/trend.py'
      - 'backend/Dockerfile'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push cron
        uses: docker/build-push-action@v3
        with:
          context: cron
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cron:latest

      - name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          context: backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask:latest
